### ISSUE TITLE
[Feature request] Add an option to define picture display size

### ISSUE THREAD

**Issue by morgandavidson** [xcapaldi/ob-d2#4]
When I compile a d2 block, for example:

```
#+begin_src d2 :file refiling.png :flags -t 4 -l elk 
  direction: right
  "leftbox1" -> "rightbox1": Comment 1
  "leftbox2" -> "rightbox2": Comment 2
  "leftbox3" -> "rightbox3": Comment 3
#+end_src
```

The size of the displayed PNG is much too big in my buffer. Also, when I export the org buffer to HTML, the picture size is too big.

It would be useful to be able to define the picture size.

**Comment by xcapaldi** [comment]
This is a feature of `org-mode` itself and not the `d2` extension. In particular since `d2` generates an image and you have likely have the default setting of `org-image-actual-width` which is `t` you are getting native width. Check the doc on that in Emacs but in summary if set to `t`, it will use the native image width, if set to a number it will try to force the image to appear in the buffer at certain width and if set to `nil` it will use any associated `#+ATTR.*` it finds and fall back on the default size.

In your particular case, I recommend setting `(setq org-image-actual-width nil)` in your config and then using `#+ATTR_HTML: ...` to set your desired size both for org-mode and for HTML export.

However because the image is the result of org block evaluation, you'll need to do more steps to ensure you can re-evaluate and not mess up the position. Check out this [suggested solution](https://emacs.stackexchange.com/questions/59900/change-emacs-generated-image-size-in-org-mode-export) and let me know if this flow works for you.

Unless I am missing a flag passed to the `d2` cli program itself that can specify image output size?

**Comment by morgandavidson** [comment]
`(setq org-image-actual-width nil)`

and
```
#+begin_src d2 :file refiling.png :flags -t 4 -l elk 
  direction: right
  "leftbox1" -> "rightbox1": Comment 1
  "leftbox2" -> "rightbox2": Comment 2
  "leftbox3" -> "rightbox3": Comment 3
#+end_src
#+ATTR_HTML: :width 800px
#+RESULTS:
```
did the trick, thank you.

Unfortunately, I didn't see a flag for the output size in d2 neither. Maybe they will implement it later.

**Comment by alixander** [comment]
@morgandavidson @xcapaldi tracking here https://github.com/terrastruct/d2/issues/1005#issuecomment-1466748464
